use crate::channel::Bandwidth::Narrow;
use crate::channel::Ctcss::Ctcss1148;
use crate::channel::CtcssDcs::{Ctcss, Dcs};
use crate::channel::Dcs::D026N;
use crate::channel::TxPower::Low;
use crate::channel::{Channel, ChannelData};

pub fn default_channels() -> Vec<Channel> {
    vec![
        Channel {
            rx_frequency: 44600625,
            tx_frequency: 44600625,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44601875,
            tx_frequency: 44601875,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44603125,
            tx_frequency: 44603125,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44604375,
            tx_frequency: 44604375,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44605625,
            tx_frequency: 44605625,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44606875,
            tx_frequency: 44606875,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44608125,
            tx_frequency: 44608125,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44609375,
            tx_frequency: 44609375,
            rx_ctcss_dcs: Ctcss(Ctcss1148),
            tx_ctcss_dcs: Ctcss(Ctcss1148),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44610625,
            tx_frequency: 44610625,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44611875,
            tx_frequency: 44611875,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44613125,
            tx_frequency: 44613125,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44614375,
            tx_frequency: 44614375,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44615625,
            tx_frequency: 44615625,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44616875,
            tx_frequency: 44616875,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44618125,
            tx_frequency: 44618125,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
        Channel {
            rx_frequency: 44619375,
            tx_frequency: 44619375,
            rx_ctcss_dcs: Dcs(D026N),
            tx_ctcss_dcs: Dcs(D026N),
            data: ChannelData {
                _unknown0: true,
                _unknown1: true,
                _unknown2: true,
                scan_add: false,
                tx_power: Low,
                _unknown3: true,
                bandwidth: Narrow,
                busy_lock: false,
            },
        },
    ]
}
